name: TruffleHog Secret Scan

on:
 workflow_dispatch:


jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: .
          extra_args: --log-level 2 --no-verification --max-depth=10 --no-fail
      - name: debug
        run: |
          echo ${BASE:-''}
