name: TruffleHog Secret Scan

on:
 workflow_dispatch:


jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run TruffleHog
        run: |
         docker run --rm -v "$PWD:/pwd" trufflesecurity/trufflehog:latest file://. \ #github-experimental \
         --github-actions --no-verification   # --object-discovery --token=${{ secrets.GH_TOKEN }}
        
